name: .NET

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'

  pull_request:
    branches: [ main ]
    paths-ignore:
    - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x.x

    - name: Restore dependencies
      run: dotnet restore TinMonkey.HL7.sln

    - name: Build
      run: dotnet build TinMonkey.HL7.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test TinMonkey.HL7.sln --configuration Release --no-build --verbosity normal

    - name: Restore tools
      run: dotnet tool restore

    - name: Generate docs
      run: dotnet livingdoc feature-folder TinMonkey.HL7.Core.Specs -t **/TestExecution.json --output docs/index.html

    - name: Commit docs changes to repo
      uses: actions-x/commit@v2
      with:
        files: docs/index.html
