name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.x.x

    - name: Restore dependencies
      run: dotnet restore TinMonkey.HL7.sln

    - name: Build
      run: dotnet build TinMonkey.HL7.sln --configuration Release --no-restore

    - name: Test
      run: dotnet test TinMonkey.HL7.sln --configuration Release --no-build --verbosity normal

    - name: Generate docs
      run: livingdoc test-assembly .\**\*.Specs.dll -t .\**\TestExecution.json --output .\doc\LivingDoc.html
